package cn.org.yxzb.camemt.pojo;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`ts_permission`")
public class TsPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.parent_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.name
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.expression
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String expression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.permission_type
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String permissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.url
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.seq
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.create_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.create_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.update_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.update_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_permission.status
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.id
     *
     * @return the value of ts_permission.id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.id
     *
     * @param id the value for ts_permission.id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.parent_id
     *
     * @return the value of ts_permission.parent_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.parent_id
     *
     * @param parentId the value for ts_permission.parent_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.name
     *
     * @return the value of ts_permission.name
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.name
     *
     * @param name the value for ts_permission.name
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.expression
     *
     * @return the value of ts_permission.expression
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.expression
     *
     * @param expression the value for ts_permission.expression
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setExpression(String expression) {
        this.expression = expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.permission_type
     *
     * @return the value of ts_permission.permission_type
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.permission_type
     *
     * @param permissionType the value for ts_permission.permission_type
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.url
     *
     * @return the value of ts_permission.url
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.url
     *
     * @param url the value for ts_permission.url
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.seq
     *
     * @return the value of ts_permission.seq
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.seq
     *
     * @param seq the value for ts_permission.seq
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.create_date
     *
     * @return the value of ts_permission.create_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.create_date
     *
     * @param createDate the value for ts_permission.create_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.create_user_id
     *
     * @return the value of ts_permission.create_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.create_user_id
     *
     * @param createUserId the value for ts_permission.create_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.update_date
     *
     * @return the value of ts_permission.update_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.update_date
     *
     * @param updateDate the value for ts_permission.update_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.update_user_id
     *
     * @return the value of ts_permission.update_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.update_user_id
     *
     * @param updateUserId the value for ts_permission.update_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_permission.status
     *
     * @return the value of ts_permission.status
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_permission.status
     *
     * @param status the value for ts_permission.status
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}