package cn.org.yxzb.camemt.pojo;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`ts_role`")
public class TsRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.parent_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.role_name
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.create_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.create_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.update_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.update_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.status
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.id
     *
     * @return the value of ts_role.id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.id
     *
     * @param id the value for ts_role.id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.parent_id
     *
     * @return the value of ts_role.parent_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.parent_id
     *
     * @param parentId the value for ts_role.parent_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.role_name
     *
     * @return the value of ts_role.role_name
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.role_name
     *
     * @param roleName the value for ts_role.role_name
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.create_user_id
     *
     * @return the value of ts_role.create_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.create_user_id
     *
     * @param createUserId the value for ts_role.create_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.create_date
     *
     * @return the value of ts_role.create_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.create_date
     *
     * @param createDate the value for ts_role.create_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.update_user_id
     *
     * @return the value of ts_role.update_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.update_user_id
     *
     * @param updateUserId the value for ts_role.update_user_id
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.update_date
     *
     * @return the value of ts_role.update_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.update_date
     *
     * @param updateDate the value for ts_role.update_date
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.status
     *
     * @return the value of ts_role.status
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.status
     *
     * @param status the value for ts_role.status
     *
     * @mbggenerated Thu Aug 08 14:18:11 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}