server:
  port: 7000
spring:
  application:
    name: came-mt
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/came_mt_v0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: cn.org.yxzb.camemt.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#Spring Security 和 jwt 的相关设置

token:
  # token 请求头的名字
  header: X_Auth_Token
  # token 加密密钥
  secret: secret
  # token 过期时间，以秒为单位，604800 是 一星期
  expiration: 604800

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace

swagger:
  enable: true